# Dockerfile.backend

# Base image
FROM node:22-alpine

# Set working directory
WORKDIR /app/backend

# Salin file package.json dan package-lock.json dulu
COPY backend/package*.json ./

# Jalankan npm install
RUN npm install

# Salin semua file dari folder backend ke dalam container
COPY backend/. .

# Jalankan server
CMD ["node", "server.js"]
