# Dockerfile.frontend
FROM node:22-alpine AS node-build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN NODE_OPTIONS="max-old-space-size=2048" npm run build

FROM nginx:alpine

COPY --from=node-build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
