version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ''
      DB_NAME: spedal
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
